# Jekyll configuration for Chris Chan's personal website
title: Chris Chan
description: Personal website of Chris Chan
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed